# Generated by Django 4.1.7 on 2023-03-25 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0003_icons_statustasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icons',
            name='icon',
            field=models.ImageField(default='no_icon.png', upload_to='icons_img', verbose_name='Иконка'),
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('type', models.CharField(default='Задача', max_length=100, verbose_name='Тип объекта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('dedline', models.DateField(verbose_name='Дата сдачи')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.icons', verbose_name='Иконка')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.projects', verbose_name='Принадлежит к проекту')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.statustasks', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
